[package]
name = "draven"
version = "1.0.0"
edition = "2021"
repository = "https://github.com/AuracleTech/draven"
license = "MIT"

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.65", features = ["full"] }
