[package]
name = "draven"
version = "1.0.2"
edition = "2021"
description = "draven parses structures of a rust project into obsidian vault graph files"
repository = "https://github.com/AuracleTech/draven"
license = "MIT"
keywords = ["cli", "draven", "obsidian", "graph"]
categories = ["command-line-utilities"]

[dependencies]
quote = "1.0.36"
syn = { version = "2.0.65", features = ["full"] }
